_tabletennisUsefulInformationShow:
    defaults: { _controller: TableTennisUsefulInformationBundle:Default:show, culture: fr }
    pattern: /{culture}/informations-utiles/{slug}.html
    requirements:
        culture: fr