imports:
    - { resource: parameters.ini }
    - { resource: security.yml }
    - { resource: user/fos_user.yml }
    - { resource: user/sonata_user.yml }
    - { resource: forum/herzult_forum.yml }
    - { resource: sonata/sonata_admin.yml }
    - { resource: sonata/sonata_doctrine_orm_admin.yml }
##    - { resource: sonata_news.yml }
    - { resource: sonata/sonata_block.yml }
    - { resource: sonata/sonata_media.yml }
    - { resource: sonata/sonata_classification.yml }
    - { resource: sonata/sonata_intl.yml }
    - { resource: sonata/sonata_cache.yml }
##    - { resource: sonata_formatter.yml }
    - { resource: google/ivory_google_map.yml }
    - { resource: tinymce/stfalcon_tinymce.yml }
    - { resource: feed/eko_feed.yml }
    - { resource: @BasePageBundle/Resources/config/admin.yml }
    - { resource: @BaseCategoryBundle/Resources/config/admin.yml }
    - { resource: @BaseNewsBundle/Resources/config/admin.yml }
    - { resource: @BaseEventBundle/Resources/config/admin.yml }
    - { resource: @BaseForumBundle/Resources/config/admin.yml }
    - { resource: @TableTennisMainBundle/Resources/config/admin.yml }
    - { resource: @TableTennisUsefulInformationBundle/Resources/config/admin.yml }
    - { resource: @TableTennisAnnouncementBundle/Resources/config/admin.yml }
    - { resource: @TableTennisLicenseeBundle/Resources/config/admin.yml }
    - { resource: @TableTennisClubBundle/Resources/config/admin.yml }
    - { resource: @TableTennisMatchTypeBundle/Resources/config/admin.yml }
    - { resource: @TableTennisPartnerBundle/Resources/config/admin.yml }
    # - { resource: @TableTennisTeamBundle/Resources/config/admin.yml }

parameters:
    base_contact.emails.contact_email_from: contact@cpfaizenay.com
    base_contact.emails.contact_email_to: [ecouvreur@yahoo.fr]

framework:
    esi:             { enabled: true }
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    # trust_proxy_headers: false # Deprecated in 2.0; will be removed in 2.3 (used trusted_proxies instead)
    trusted_proxies: ~
    session:         ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    cache:            %kernel.cache_dir%/twig
    globals:
        facebook_uri: %facebook.uri%
    form:
        resources:
            - 'SonataCoreBundle:Form:datepicker.html.twig'
            - 'SonataMediaBundle:Form:media_widgets.html.twig'

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [BaseNewsBundle]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        closure:
            jar: "%kernel.root_dir%/Resources/utilities/java/compiler.jar"
        yui_css:
            jar: "%kernel.root_dir%/Resources/utilities/java/yuicompressor-2.4.7.jar"
        yui_js:
            jar: "%kernel.root_dir%/Resources/utilities/java/yuicompressor-2.4.7.jar"
        optipng:
            bin: "%kernel.root_dir%/Resources/utilities/optipng-0.7.5"
            apply_to: "\.png$"
            level:    3
        jpegoptim:
            bin: "%kernel.root_dir%/Resources/utilities/jpegoptim-1.4.1"
            strip_all: true
            max: 70
    twig:
        functions:
            jpegoptim: ~
#        yui_css:
#            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.8.jar"
#        yui_js:
#            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.8.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        mapping_types:
            enum: string
            set: string
            varbinary: string
            tinyblob: text
        types:
            json: Sonata\Doctrine\Types\JsonType

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

#                    gedmo_translatable:
#                        type: annotation
#                        prefix: Gedmo\Translatable\Entity
#                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"
#                        alias: GedmoTranslatable # this one is optional and will default to the name set for the mapping
#                        is_bundle: false
#                    gedmo_translator:
#                        type: annotation
#                        prefix: Gedmo\Translator\Entity
#                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translator/Entity"
#                        alias: GedmoTranslator # this one is optional and will default to the name set for the mapping
#                        is_bundle: false
#                    gedmo_loggable:
#                        type: annotation
#                        prefix: Gedmo\Loggable\Entity
#                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
#                        alias: GedmoLoggable # this one is optional and will default to the name set for the mapping
#                        is_bundle: false
#                    gedmo_tree:
#                        type: annotation
#                        prefix: Gedmo\Tree\Entity
#                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"
#                        alias: GedmoTree # this one is optional and will default to the name set for the mapping
#                        is_bundle: false

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    port:      "%mailer_port%"
    spool:     { type: memory }

gregwar_captcha:
    quality: 80
    invalid_message: "Le code de vérification est incorrecte"
    distortion: false

#Extras conf
stof_doctrine_extensions:
    default_locale: fr_FR
    orm:
        default:
            timestampable: true
            sluggable: true

services:
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

    app.twig_extension:
        class: App\TwigExtensionBundle\Extensions\SonataMediaPathExtension
        public: false
        arguments:
            - @service_container
            - @sonata.media.manager.media
        tags:
            - { name: twig.extension }

    # inscription utilisateur
    application_sonata_user.registration.form.type:
        class: Application\Sonata\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: application_sonata_user_registration }