sonata_admin:
    security:
        handler: sonata.admin.security.handler.role

    title:      'CPF Aizenay'
    title_logo: '/images/default/logo.png'
    templates:
        user_block:           'SonataAdminBundle:Core:user_block.html.twig'
        add_block:            'SonataAdminBundle:Core:add_block.html.twig'
        layout:               'SonataAdminBundle::standard_layout.html.twig'
        ajax:                 'SonataAdminBundle::ajax_layout.html.twig'
        dashboard:            'SonataAdminBundle:Core:dashboard.html.twig'
        search:               'SonataAdminBundle:Core:search.html.twig'
        list:                 'SonataAdminBundle:CRUD:list.html.twig'
        filter:               'SonataAdminBundle:Form:filter_admin_fields.html.twig'
        show:                 'SonataAdminBundle:CRUD:show.html.twig'
        show_compare:         'SonataAdminBundle:CRUD:show_compare.html.twig'
        edit:                 'ApplicationSonataAdminBundle:CRUD:edit.html.twig'
        preview:              'SonataAdminBundle:CRUD:preview.html.twig'
        history:              'SonataAdminBundle:CRUD:history.html.twig'
        acl:                  'SonataAdminBundle:CRUD:acl.html.twig'
        history_revision_timestamp:  'SonataAdminBundle:CRUD:history_revision_timestamp.html.twig'
        action:               'SonataAdminBundle:CRUD:action.html.twig'
        select:               'SonataAdminBundle:CRUD:list__select.html.twig'
        list_block:           'SonataAdminBundle:Block:block_admin_list.html.twig'
        search_result_block:  'SonataAdminBundle:Block:block_search_result.html.twig'
        short_object_description:  'ApplicationSonataAdminBundle:Helper:short-object-description.html.twig'
        delete:               'SonataAdminBundle:CRUD:delete.html.twig'
        batch:                'SonataAdminBundle:CRUD:list__batch.html.twig'
        batch_confirmation:   'SonataAdminBundle:CRUD:batch_confirmation.html.twig'
        inner_list_row:       'SonataAdminBundle:CRUD:list_inner_row.html.twig'
        outer_list_rows_mosaic:  'SonataAdminBundle:CRUD:list_outer_rows_mosaic.html.twig'
        outer_list_rows_list:  'SonataAdminBundle:CRUD:list_outer_rows_list.html.twig'
        outer_list_rows_tree:  'SonataAdminBundle:CRUD:list_outer_rows_tree.html.twig'
        base_list_field:      'SonataAdminBundle:CRUD:base_list_field.html.twig'
        pager_links:          'SonataAdminBundle:Pager:links.html.twig'
        pager_results:        'SonataAdminBundle:Pager:results.html.twig'
        tab_menu_template:    'SonataAdminBundle:Core:tab_menu_template.html.twig'
        knp_menu_template:    'SonataAdminBundle:Menu:sonata_menu.html.twig'
    assets:
        stylesheets:

            # Defaults:
            - bundles/sonatacore/vendor/bootstrap/dist/css/bootstrap.min.css
            - bundles/sonatacore/vendor/components-font-awesome/css/font-awesome.min.css
            - bundles/sonatacore/vendor/ionicons/css/ionicons.min.css
            - bundles/sonataadmin/vendor/admin-lte/dist/css/AdminLTE.min.css
            - bundles/sonataadmin/vendor/admin-lte/dist/css/skins/skin-black.min.css
            - bundles/sonataadmin/vendor/iCheck/skins/flat/blue.css
            - bundles/sonatacore/vendor/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css
            - bundles/sonataadmin/vendor/jqueryui/themes/base/jquery-ui.css
            - bundles/sonatacore/vendor/select2/select2.css
            - bundles/sonatacore/vendor/select2-bootstrap-css/select2-bootstrap.min.css
            - bundles/sonataadmin/vendor/x-editable/dist/bootstrap3-editable/css/bootstrap-editable.css
            - bundles/sonataadmin/css/styles.css
            - bundles/sonataadmin/css/layout.css
            - bundles/sonataadmin/css/tree.css
            # Customs:
            - bundles/applicationsonataadmin/css/main.css
        javascripts:

            # Defaults:
            - bundles/sonatacore/vendor/jquery/dist/jquery.min.js
            - bundles/sonataadmin/vendor/jquery.scrollTo/jquery.scrollTo.min.js
            - bundles/sonatacore/vendor/moment/min/moment.min.js
            - bundles/sonatacore/vendor/bootstrap/dist/js/bootstrap.min.js
            - bundles/sonatacore/vendor/eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js
            - bundles/sonataadmin/vendor/jqueryui/ui/minified/jquery-ui.min.js
            - bundles/sonataadmin/vendor/jqueryui/ui/minified/i18n/jquery-ui-i18n.min.js
            - bundles/sonataadmin/jquery/jquery.form.js
            - bundles/sonataadmin/jquery/jquery.confirmExit.js
            - bundles/sonataadmin/vendor/x-editable/dist/bootstrap3-editable/js/bootstrap-editable.min.js
            - bundles/sonatacore/vendor/select2/select2.min.js
            - bundles/sonataadmin/vendor/admin-lte/dist/js/app.min.js
            - bundles/sonataadmin/vendor/iCheck/icheck.min.js
            - bundles/sonataadmin/vendor/slimScroll/jquery.slimscroll.min.js
            - bundles/sonataadmin/Admin.js
            - bundles/sonataadmin/treeview.js
    dashboard:
        blocks:
            -   
                position: left
                type: sonata.admin.block.admin_list
                settings:
                    groups: [base.admin.group.website, base.admin.group.article]
            -   
                position: right
                type: sonata.block.service.text
                settings:
                    content: >
                        <h2>Bienvenue sur l'administration</h2>
                        <p>En fonction de vos droits, vous avez accès à différentes parties par le biais du menu de gauche</p> <br />
            -  
                position: right
                type: sonata.admin.block.admin_list
                settings:
                    groups: [sonata_media, sonata_user]
            # -   
            #     position: right
            #     type: sonata.admin.block.admin_list
            #     settings: 
            #         groups: [sonata_media, sonata_user, geo, seo_services, seo_sitemap, seo_redirections, supervision, configuration, system_log, system_dev]
        groups:
            # base.admin.group.website:
            #     label: "Gestion du site"
            #     icon:  '<i class="fa fa-sitemap"></i>'
            #     items:
            #         - base.category.admin.menu
            #         - base.category.admin.footer
            base.admin.group.article:
                label: "Gestion du contenu"
                icon:  '<i class="fa fa-pencil"></i>'
                items:
                    - base.page.admin.page
                    #- base.category.admin.categoryNews
                    - base.page.admin.news
                    # - base.page.admin.event
                    - tabletennis.useful.admin.useful
                    - tabletennis.announcement.admin.announcement
            base.admin.group.forum:
                label: "Gestion du forum"
                icon:  '<i class="fa fa-comments fa-fw"></i>'
                items:
                    - base.forum.admin.category
                    - base.forum.admin.topic
                    - base.forum.admin.post
            sonata_media:
                label: "Gestion des médias"
                icon:  '<i class="fa fa-file"></i>'
                items:
                    - sonata.media.admin.media
                    - sonata.media.admin.gallery
            sonata_user:
                label: "Gestion des utilisateurs"
                icon:  '<i class="fa fa-user"></i>'
                items:
                    - sonata.user.admin.user
                    - sonata.user.admin.group
#            geo:
#                items:
#                    - sonata.media.admin.gallery
#                    - sonata.media.admin.gallery
#                    - sonata.media.admin.gallery
#                    - sonata.media.admin.gallery
#            seo_services:
#                items:
#                    - sonata.media.admin.gallery
#                    - sonata.media.admin.gallery
#                    - sonata.media.admin.gallery
#                    - sonata.media.admin.gallery
#            seo_sitemap:
#                items:
#                    - sonata.media.admin.gallery
#            seo_redirections:
#                items:
#                    - sonata.media.admin.gallery
#            supervision:
#                items:
#                    - sonata.media.admin.gallery
#                    - sonata.media.admin.gallery
#            configuration:
#                items:
#                    - sonata.media.admin.gallery
#            system_log:
#                items:
#                    - sonata.media.admin.gallery
#                    - sonata.media.admin.gallery
#            system_dev:
#                items:
#                    - sonata.media.admin.gallery
#                    - sonata.media.admin.gallery
#            gallery:
#                items:
#                    - tabletennis.announcement.admin.announcement
            tabletennis.admin.group.tabletennis:
                label: "Tennis de table"
                icon:  '<i class="fa fa-trophy"></i>'
                items:
                    - tabletennis.licensee.admin.licensee
                    # - tabletennis.licensee.admin.licenseePoint
                    # - tabletennis.licensee.admin.licenseeMatch
                    - tabletennis.club.admin.club
            #         - tabletennis.team.admin.team
                    # - tabletennis.matchType.admin.matchType
                    - tabletennis.partner.admin.partner
    # set to true to persist filter settings per admin module in the user's session
    persist_filters: true