parameters:
#    table_tennis_home_page_frontend.example.class: TableTennis\HomePageFrontendBundle\Example

services:
#    table_tennis_home_page_frontend.example:
#        class: %table_tennis_home_page_frontend.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
