services:
    base.page.admin.page:
        class: Base\PageBundle\Admin\PageAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "base.admin.group.article", label: "Page" }
        arguments: 
            - ~
            - Base\PageBundle\Entity\Page
            - BasePageBundle:PageAdmin
            - '@service_container'
        calls:
            - [setTranslationDomain, [BasePageBundle]]