services:
    base.page.admin.event:
        class: Base\EventBundle\Admin\EventAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "base.admin.group.article", label: "Evénements" }
        arguments: 
            - ~
            - Base\EventBundle\Entity\Event
            - BaseEventBundle:EventAdmin
            - '@service_container'
        calls:
            - [setTranslationDomain, [BaseEventBundle]]