services:
    base.category.admin.categoryNews:
        class: Base\CategoryBundle\Admin\CategoryNewsAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "base.admin.group.article", label: "Thèmes des actualités" }
        arguments: 
            - ~
            - Base\CategoryBundle\Entity\CategoryNews
            - BaseCategoryBundle:CategoryNewsAdmin
            - '@service_container'
        calls:
            - [setTranslationDomain, [BaseCategoryBundle]]