_tableTennisScoringTableIndex:
    defaults: { _controller: TableTennisScoringTableBundle:Default:index, culture: fr }
    pattern: /{culture}/bareme-des-points.html
    requirements:
        culture: fr